### ISSUE TITLE
Cannot read properties of undefined (reading 'getDisplayMedia')

### ISSUE THREAD

**Issue by Vaisakhkm2625** [josephDev123/screen-recorder#1]
Hi

i have tried your app, cloned it to my computer and started a simple server, but it always giving me this error
<img width="465" alt="image" src="https://user-images.githubusercontent.com/68694876/150882299-e56d3a02-c51f-4a62-8ea7-1d2c2f86753a.png">
I opened it in edge browser, 

do you have any idea on this...

 stream = await navigator.mediaDevices.getDisplayMedia(gdmOptions); 
 
 but navigator object don't have mediaDevices or getDisplayMedia()
 
 while, https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture#capturing_screen_contents
 documentation, they are showing the same, and demo in that is working on my system....
<img width="887" alt="image" src="https://user-images.githubusercontent.com/68694876/150883931-893e9e6b-a2b7-4bc5-81b5-0d6c98707d92.png">

  but that demo was within a iframe
  i copied that code and put it in a index.html file, and again same thing happened
 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/68694876/150883754-12d17af6-31ab-46c0-9212-d7443f543ab7.png">

I am sure that it is some kind of permission error, but can you help on this please

**Comment by Vaisakhkm2625** [comment]
sorry, my bad....

now only i understood that it needed HTTPS to allow this....
otherwise navigator wouldn't have mediaDevices property

**Comment by Vaisakhkm2625** [comment]
Really nice project.... i had to record desktop of work system (windows 10), but my company don't allow any extra apps, and online recording urls are blocked... but finally, i made self signed python server
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68694876/150892813-18362b84-7887-48e3-93d8-eefd5cf220ca.png">
then i just forked yourproject and turned on github pages.... worked wonderfully...

thanks....

**Comment by josephDev123** [comment]
Thanks for finding my project interesting.

**Comment by Vaisakhkm2625** [comment]
I have tried changed some things like made downloading format from 'mkv'(which is kind of terrible format) to 'webm' and tring to add a help button...
While keeping the minimilistic nature of your project...

Can i give you a pull request, are you interested!?
